---
- name: Install and Configure Nginx
  hosts: all
  become: true

  tasks:

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Enable Nginx Service
      service:
        name: nginx
        enabled: yes

    - name: Start Nginx Service
      service:
        name: nginx
        state: started

    - name: Copy Website to Nginx
      copy:
        src: ../website/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'